Repository sass/libsass, pull requests merged in 2018-11, with the labels that each got.

#2737 Fix selector unification ordering
  src/ast.cpp
  src/ast.hpp
  src/constants.cpp
  src/constants.hpp
Labels: Dev - Test Written

#2761 Implement passing arguments to @content
  src/ast.hpp
  src/constants.cpp
  src/constants.hpp
  src/debugger.hpp
  src/expand.cpp
  src/parser.cpp
  src/prelexer.cpp
  src/prelexer.hpp
Labels: Feature - Implementation

#2768 Roundhouse Cleanup 02
  Makefile.conf
  src/ast.cpp
  src/ast.hpp
  src/ast_sel_cmp.cpp
  src/ast_sel_unify.cpp
  src/ast_selectors.cpp
  src/ast_selectors.hpp
  src/ast_values.cpp
  src/ast_values.hpp
  src/debugger.hpp
  src/fn_miscs.cpp
  win/libsass.targets
  win/libsass.vcxproj.filters
Labels: Dev - WIP

#2770 Roundhouse cleanup 03
  Makefile.conf
  src/ast.cpp
  src/ast.hpp
  src/ast_def_macros.hpp
  src/ast_sel_cmp.cpp
  src/ast_selectors.cpp
  src/ast_selectors.hpp
  src/ast_supports.cpp
  src/ast_supports.hpp
  src/ast_values.cpp
  src/ast_values.hpp
  src/debugger.hpp
  src/fn_strings.cpp
  src/inspect.cpp
  src/units.cpp
  src/units.hpp
  win/libsass.targets
  win/libsass.vcxproj.filters
Labels: Dev - WIP

#2774 Refactor loops in Selector::unify_with
  src/ast_sel_unify.cpp
Labels: Dev - PR Ready
