Repository sass/libsass, pull requests merged in 2018-02, with the labels that each got.

#2563 Fix css test for interpolated numbers
  src/eval.cpp
Labels: Dev - PR Ready

#2564 Support var() in rbga short-hand syntax
  src/functions.cpp
Labels: Dev - PR Ready, Dev - Test Written, Sass 3.5

#2565 Fix nesting check for at-root
  src/check_nesting.cpp
  src/parser.cpp
  src/parser.hpp
Labels: Dev - PR Ready, Dev - Test Written
