Repository sass/libsass, pull requests merged in 2018-03, with the labels that each got.

#2570 Fix null pointer access in nesting check
  src/check_nesting.cpp
Labels: Back port to 3.4, Dev - PR Ready

#2571 Add special check nesting handling for @else
  src/check_nesting.cpp
  src/check_nesting.hpp
Labels: Back port to 3.4, Dev - PR Ready, Dev - Test Written

#2572 Fix parsing of @supports declarations
  src/parser.cpp
Labels: Dev - PR Ready, Dev - Test Written

#2559 Enable nesting checks for all includes
  src/context.cpp
Labels: Dev - PR Ready

#2589 Fix win UNC path handling for dot and dotdot directories
  src/file.cpp
Labels: Back port to 3.4, Dev - PR Ready

#2587 Fix parsing of block comments to ignore css string rules
  src/ast.hpp
  src/debugger.hpp
  src/eval.cpp
  src/parser.cpp
  src/parser.hpp
  src/util.cpp
  src/util.hpp
Labels: Back port to 3.4, Dev - PR Ready

#2586 Implement more detailed backtraces
  Makefile.conf
  src/ast.cpp
  src/ast.hpp
  src/ast_def_macros.hpp
  src/ast_fwd_decl.hpp
  src/backtrace.cpp
  src/backtrace.hpp
  src/bind.cpp
  src/check_nesting.cpp
  src/check_nesting.hpp
  src/context.cpp
  src/context.hpp
  src/cssize.cpp
  src/cssize.hpp
  src/debugger.hpp
  src/error_handling.cpp
  src/error_handling.hpp
  src/eval.cpp
  src/eval.hpp
  src/expand.cpp
  src/expand.hpp
  src/extend.cpp
  src/functions.cpp
  src/functions.hpp
  src/operators.cpp
  src/operators.hpp
  src/output.cpp
  src/parser.cpp
  src/parser.hpp
  src/sass_context.cpp
  src/sass_values.cpp
  win/libsass.targets
  win/libsass.vcxproj.filters
Labels: Back port to 3.4, Dev - PR Ready

#2597 Adjust output/error for modulo zero operation
  src/operators.cpp
Labels: Back port to 3.4, Back port to 3.5, Dev - PR Ready

#2601 Fix automake build if sassc is missing
  GNUmakefile.am
  configure.ac
  script/tap-runner
Labels: Back port to 3.4 stable, Back port to 3.5 stable

#2602 Upgrade sass2scss to version 1.1.2
  src/sass2scss.cpp
Labels: Back port to 3.4 stable, Back port to 3.5 stable

#2603 Allow colors in `@at` directives
  src/parser.cpp
Labels: Back port to 3.4 stable, Back port to 3.5 stable

#2606 Fix edge case converting achromatic colors to HSL
  src/fn_colors.cpp
Labels: Back port to 3.4 stable, Back port to 3.5 stable, Dev - PR Ready

#2607 Delay interpolated expression as in regular CSS
  src/debugger.hpp
  src/parser.cpp
Labels: Back port to 3.4 stable, Back port to 3.5 stable, Dev - PR Ready

#2624 Fix merging of nested media queries with not
  src/cssize.cpp
Labels: Dev - PR Ready, Dev - Test Written, ported to 3.5

#2626 Fix regression in parsing selector with trailing escaped colon
  src/parser.cpp
Labels: Back port to 3.5 stable, Dev - PR Ready, Dev - Test Written
