Repository sass/libsass, pull requests merged in 2019-10, with the labels that each got.

#2995 Fix selector `isInvisible` logic
  src/ast_selectors.cpp
Labels: Dev - PR Ready

#2996 Fix evaluation of unary expressions in loops
  src/eval.cpp
Labels: Dev - PR Ready

#2990 unrecognized psuedos with arguments parse as declaration-values
  src/parser.cpp
Labels: Dev - PR Ready, Dev - Test Written

#2997 Fix attribute selector equality (include modifier)
  src/ast_sel_cmp.cpp
Labels: Dev - PR Ready

#3007 Fix extend issue being stuck in endless loop
  src/eval_selectors.cpp
  src/expand.cpp
  src/expand.hpp
  src/extender.cpp
  src/extender.hpp
Labels: Dev - Needs Test, Dev - PR Ready

#3015 Fix possible memory leak in permutation function
  src/permutate.hpp
Labels: Dev - PR Ready

#3022 Extend `error_src` lifetime on c-api context
  docs/api-context-internal.md
  docs/api-context.md
  include/sass/context.h
  src/parser.cpp
  src/sass_context.cpp
  src/sass_context.hpp
Labels: Dev - PR Ready
